/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'firewallRules', { get: function () { return require('./firewall-rules'); } });
Object.defineProperty(exports, 'floatingIpAddress', { get: function () { return require('./floating-ip-address'); } });
Object.defineProperty(exports, 'gateway', { get: function () { return require('./gateway'); } });
Object.defineProperty(exports, 'gatewayConnection', { get: function () { return require('./gateway-connection'); } });
Object.defineProperty(exports, 'gatewayConnectionTunnel', { get: function () { return require('./gateway-connection-tunnel'); } });
Object.defineProperty(exports, 'kubernetesCluster', { get: function () { return require('./kubernetes-cluster'); } });
Object.defineProperty(exports, 'kubernetesNodeGroup', { get: function () { return require('./kubernetes-node-group'); } });
Object.defineProperty(exports, 'loadbalancer', { get: function () { return require('./loadbalancer'); } });
Object.defineProperty(exports, 'loadbalancerBackend', { get: function () { return require('./loadbalancer-backend'); } });
Object.defineProperty(exports, 'loadbalancerBackendTlsConfig', { get: function () { return require('./loadbalancer-backend-tls-config'); } });
Object.defineProperty(exports, 'loadbalancerDynamicBackendMember', { get: function () { return require('./loadbalancer-dynamic-backend-member'); } });
Object.defineProperty(exports, 'loadbalancerDynamicCertificateBundle', { get: function () { return require('./loadbalancer-dynamic-certificate-bundle'); } });
Object.defineProperty(exports, 'loadbalancerFrontend', { get: function () { return require('./loadbalancer-frontend'); } });
Object.defineProperty(exports, 'loadbalancerFrontendRule', { get: function () { return require('./loadbalancer-frontend-rule'); } });
Object.defineProperty(exports, 'loadbalancerFrontendTlsConfig', { get: function () { return require('./loadbalancer-frontend-tls-config'); } });
Object.defineProperty(exports, 'loadbalancerManualCertificateBundle', { get: function () { return require('./loadbalancer-manual-certificate-bundle'); } });
Object.defineProperty(exports, 'loadbalancerResolver', { get: function () { return require('./loadbalancer-resolver'); } });
Object.defineProperty(exports, 'loadbalancerStaticBackendMember', { get: function () { return require('./loadbalancer-static-backend-member'); } });
Object.defineProperty(exports, 'managedDatabaseLogicalDatabase', { get: function () { return require('./managed-database-logical-database'); } });
Object.defineProperty(exports, 'managedDatabaseMysql', { get: function () { return require('./managed-database-mysql'); } });
Object.defineProperty(exports, 'managedDatabaseOpensearch', { get: function () { return require('./managed-database-opensearch'); } });
Object.defineProperty(exports, 'managedDatabasePostgresql', { get: function () { return require('./managed-database-postgresql'); } });
Object.defineProperty(exports, 'managedDatabaseRedis', { get: function () { return require('./managed-database-redis'); } });
Object.defineProperty(exports, 'managedDatabaseUser', { get: function () { return require('./managed-database-user'); } });
Object.defineProperty(exports, 'managedObjectStorage', { get: function () { return require('./managed-object-storage'); } });
Object.defineProperty(exports, 'managedObjectStoragePolicy', { get: function () { return require('./managed-object-storage-policy'); } });
Object.defineProperty(exports, 'managedObjectStorageUser', { get: function () { return require('./managed-object-storage-user'); } });
Object.defineProperty(exports, 'managedObjectStorageUserAccessKey', { get: function () { return require('./managed-object-storage-user-access-key'); } });
Object.defineProperty(exports, 'managedObjectStorageUserPolicy', { get: function () { return require('./managed-object-storage-user-policy'); } });
Object.defineProperty(exports, 'network', { get: function () { return require('./network'); } });
Object.defineProperty(exports, 'objectStorage', { get: function () { return require('./object-storage'); } });
Object.defineProperty(exports, 'router', { get: function () { return require('./router'); } });
Object.defineProperty(exports, 'server', { get: function () { return require('./server'); } });
Object.defineProperty(exports, 'serverGroup', { get: function () { return require('./server-group'); } });
Object.defineProperty(exports, 'storage', { get: function () { return require('./storage'); } });
Object.defineProperty(exports, 'tag', { get: function () { return require('./tag'); } });
Object.defineProperty(exports, 'dataUpcloudHosts', { get: function () { return require('./data-upcloud-hosts'); } });
Object.defineProperty(exports, 'dataUpcloudIpAddresses', { get: function () { return require('./data-upcloud-ip-addresses'); } });
Object.defineProperty(exports, 'dataUpcloudKubernetesCluster', { get: function () { return require('./data-upcloud-kubernetes-cluster'); } });
Object.defineProperty(exports, 'dataUpcloudManagedDatabaseMysqlSessions', { get: function () { return require('./data-upcloud-managed-database-mysql-sessions'); } });
Object.defineProperty(exports, 'dataUpcloudManagedDatabaseOpensearchIndices', { get: function () { return require('./data-upcloud-managed-database-opensearch-indices'); } });
Object.defineProperty(exports, 'dataUpcloudManagedDatabasePostgresqlSessions', { get: function () { return require('./data-upcloud-managed-database-postgresql-sessions'); } });
Object.defineProperty(exports, 'dataUpcloudManagedDatabaseRedisSessions', { get: function () { return require('./data-upcloud-managed-database-redis-sessions'); } });
Object.defineProperty(exports, 'dataUpcloudManagedObjectStoragePolicies', { get: function () { return require('./data-upcloud-managed-object-storage-policies'); } });
Object.defineProperty(exports, 'dataUpcloudManagedObjectStorageRegions', { get: function () { return require('./data-upcloud-managed-object-storage-regions'); } });
Object.defineProperty(exports, 'dataUpcloudNetworks', { get: function () { return require('./data-upcloud-networks'); } });
Object.defineProperty(exports, 'dataUpcloudStorage', { get: function () { return require('./data-upcloud-storage'); } });
Object.defineProperty(exports, 'dataUpcloudTags', { get: function () { return require('./data-upcloud-tags'); } });
Object.defineProperty(exports, 'dataUpcloudZone', { get: function () { return require('./data-upcloud-zone'); } });
Object.defineProperty(exports, 'dataUpcloudZones', { get: function () { return require('./data-upcloud-zones'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

